# Generated by Django 2.1.2 on 2018-10-24 15:07

import ads.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_accesspoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.URLField(verbose_name='Advertised URL')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start showing')),
                ('publication_date_end', models.DateTimeField(default=ads.models.now_plus_1_day, verbose_name='Stop showing')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('weight', models.IntegerField(default=1, help_text='Weight of the ad relative to other ads in the same zone.<br />Ad with higher weight will be displayed more frequently.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Advertiser', verbose_name='Ad Provider')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Category', verbose_name='Category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='ad-images', verbose_name='Image')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.Ad', verbose_name='Ad')),
            ],
        ),
    ]
