# Generated by Django 2.1.2 on 2018-10-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20181026_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Venue', verbose_name='Venue'),
        ),
    ]
