# Generated by Django 2.1.2 on 2018-10-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('title',), 'verbose_name': 'Venue', 'verbose_name_plural': 'Venues'},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='venue',
        ),
    ]
