# Generated by Django 2.1.2 on 2018-10-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20181026_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='ads.Ad', verbose_name='Ad'),
        ),
    ]
