# Generated by Django 2.1.2 on 2018-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20181026_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='venue',
        ),
        migrations.AddField(
            model_name='ad',
            name='venue',
            field=models.ManyToManyField(blank=True, null=True, to='ads.Venue', verbose_name='Venue'),
        ),
    ]
