# Generated by Django 2.1.2 on 2018-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20181026_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='venue',
            field=models.ManyToManyField(to='ads.Venue', verbose_name='Venue'),
        ),
    ]
