# Generated by Django 2.1.2 on 2018-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_auto_20181026_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='venue',
        ),
        migrations.AddField(
            model_name='ad',
            name='venues',
            field=models.ManyToManyField(to='ads.Venue', verbose_name='Venues'),
        ),
    ]
