# Generated by Django 2.1.2 on 2018-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20181026_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Venue Group'),
        ),
    ]
