# Generated by Django 2.1.2 on 2018-11-05 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_venue_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP Address')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Source Session ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.Ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Ad Click',
                'verbose_name_plural': 'Ad Clicks',
            },
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP Address')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Source Session ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.Ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Ad Impression',
                'verbose_name_plural': 'Ad Impressions',
            },
        ),
        migrations.AlterIndexTogether(
            name='impression',
            index_together={('ad', 'session_id')},
        ),
        migrations.AlterIndexTogether(
            name='click',
            index_together={('ad', 'session_id')},
        ),
    ]
