# Generated by Django 2.1.2 on 2018-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_auto_20181105_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='zone',
        ),
        migrations.AddField(
            model_name='adimage',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone'),
        ),
    ]
