# Generated by Django 2.1.2 on 2018-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20181106_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimage',
            name='device',
            field=models.CharField(default='sm', editable=False, max_length=2, verbose_name='Device'),
        ),
    ]
