# Generated by Django 2.1.2 on 2018-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_auto_20181106_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='device',
            field=models.CharField(choices=[('xs', 'Smartphones'), ('sm', 'Tablets'), ('md', 'Small Desktops'), ('lg', 'Large Desktops')], max_length=2, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='zone',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('header', 'Header'), ('sidebar', 'Sidebar')], max_length=50, null=True, verbose_name='Zone'),
        ),
    ]
